/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hopper.server.thrift;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.util.*;

public class ExpectStatusException extends Exception implements org.apache.thrift.TBase<ExpectStatusException, ExpectStatusException._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ExpectStatusException");

  private static final org.apache.thrift.protocol.TField ACTUAL_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("actualStatus", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ExpectStatusExceptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ExpectStatusExceptionTupleSchemeFactory());
  }

  public int actualStatus; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACTUAL_STATUS((short)1, "actualStatus");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACTUAL_STATUS
          return ACTUAL_STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACTUALSTATUS_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACTUAL_STATUS, new org.apache.thrift.meta_data.FieldMetaData("actualStatus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ExpectStatusException.class, metaDataMap);
  }

  public ExpectStatusException() {
  }

  public ExpectStatusException(
    int actualStatus)
  {
    this();
    this.actualStatus = actualStatus;
    setActualStatusIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ExpectStatusException(ExpectStatusException other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.actualStatus = other.actualStatus;
  }

  public ExpectStatusException deepCopy() {
    return new ExpectStatusException(this);
  }

  @Override
  public void clear() {
    setActualStatusIsSet(false);
    this.actualStatus = 0;
  }

  public int getActualStatus() {
    return this.actualStatus;
  }

  public ExpectStatusException setActualStatus(int actualStatus) {
    this.actualStatus = actualStatus;
    setActualStatusIsSet(true);
    return this;
  }

  public void unsetActualStatus() {
    __isset_bit_vector.clear(__ACTUALSTATUS_ISSET_ID);
  }

  /** Returns true if field actualStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetActualStatus() {
    return __isset_bit_vector.get(__ACTUALSTATUS_ISSET_ID);
  }

  public void setActualStatusIsSet(boolean value) {
    __isset_bit_vector.set(__ACTUALSTATUS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ACTUAL_STATUS:
      if (value == null) {
        unsetActualStatus();
      } else {
        setActualStatus((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ACTUAL_STATUS:
      return Integer.valueOf(getActualStatus());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ACTUAL_STATUS:
      return isSetActualStatus();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ExpectStatusException)
      return this.equals((ExpectStatusException)that);
    return false;
  }

  public boolean equals(ExpectStatusException that) {
    if (that == null)
      return false;

    boolean this_present_actualStatus = true;
    boolean that_present_actualStatus = true;
    if (this_present_actualStatus || that_present_actualStatus) {
      if (!(this_present_actualStatus && that_present_actualStatus))
        return false;
      if (this.actualStatus != that.actualStatus)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ExpectStatusException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ExpectStatusException typedOther = (ExpectStatusException)other;

    lastComparison = Boolean.valueOf(isSetActualStatus()).compareTo(typedOther.isSetActualStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActualStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.actualStatus, typedOther.actualStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ExpectStatusException(");
    boolean first = true;

    sb.append("actualStatus:");
    sb.append(this.actualStatus);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ExpectStatusExceptionStandardSchemeFactory implements SchemeFactory {
    public ExpectStatusExceptionStandardScheme getScheme() {
      return new ExpectStatusExceptionStandardScheme();
    }
  }

  private static class ExpectStatusExceptionStandardScheme extends StandardScheme<ExpectStatusException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ExpectStatusException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACTUAL_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.actualStatus = iprot.readI32();
              struct.setActualStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ExpectStatusException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ACTUAL_STATUS_FIELD_DESC);
      oprot.writeI32(struct.actualStatus);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ExpectStatusExceptionTupleSchemeFactory implements SchemeFactory {
    public ExpectStatusExceptionTupleScheme getScheme() {
      return new ExpectStatusExceptionTupleScheme();
    }
  }

  private static class ExpectStatusExceptionTupleScheme extends TupleScheme<ExpectStatusException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ExpectStatusException struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetActualStatus()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetActualStatus()) {
        oprot.writeI32(struct.actualStatus);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ExpectStatusException struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.actualStatus = iprot.readI32();
        struct.setActualStatusIsSet(true);
      }
    }
  }

}

