/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.hopper.server.avro;

@SuppressWarnings("all")
public interface ClientService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ClientService\",\"namespace\":\"com.hopper.server\",\"types\":[{\"type\":\"record\",\"name\":\"ConnectionException\",\"fields\":[]}],\"messages\":{\"connect\":{\"request\":[],\"response\":\"string\"},\"reconnect\":{\"request\":[{\"name\":\"sessionId\",\"type\":\"string\"}],\"response\":\"int\"},\"disconnect\":{\"request\":[],\"response\":\"null\",\"one-way\":true},\"ping\":{\"request\":[],\"response\":\"string\"},\"create\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"owner\",\"type\":\"string\"},{\"name\":\"initStatus\",\"type\":\"int\"},{\"name\":\"invalidateStatus\",\"type\":\"int\"}],\"response\":\"int\"},\"updateStatus\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"expectStatus\",\"type\":\"int\"},{\"name\":\"newStatus\",\"type\":\"int\"},{\"name\":\"owner\",\"type\":\"string\"},{\"name\":\"lease\",\"type\":\"int\"}],\"response\":\"int\"},\"updateLease\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"expectStatus\",\"type\":\"int\"},{\"name\":\"owner\",\"type\":\"string\"},{\"name\":\"lease\",\"type\":\"int\"}],\"response\":\"int\"},\"watch\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"expectStatus\",\"type\":\"int\"}],\"response\":\"int\"}}}");
  java.lang.CharSequence connect() throws org.apache.avro.AvroRemoteException;
  int reconnect(java.lang.CharSequence sessionId) throws org.apache.avro.AvroRemoteException;
  void disconnect();
  java.lang.CharSequence ping() throws org.apache.avro.AvroRemoteException;
  int create(java.lang.CharSequence key, java.lang.CharSequence owner, int initStatus, int invalidateStatus) throws org.apache.avro.AvroRemoteException;
  int updateStatus(java.lang.CharSequence key, int expectStatus, int newStatus, java.lang.CharSequence owner, int lease) throws org.apache.avro.AvroRemoteException;
  int updateLease(java.lang.CharSequence key, int expectStatus, java.lang.CharSequence owner, int lease) throws org.apache.avro.AvroRemoteException;
  int watch(java.lang.CharSequence key, int expectStatus) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends ClientService {
    public static final org.apache.avro.Protocol PROTOCOL = ClientService.PROTOCOL;
    void connect(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void reconnect(java.lang.CharSequence sessionId, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void ping(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void create(java.lang.CharSequence key, java.lang.CharSequence owner, int initStatus, int invalidateStatus, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void updateStatus(java.lang.CharSequence key, int expectStatus, int newStatus, java.lang.CharSequence owner, int lease, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void updateLease(java.lang.CharSequence key, int expectStatus, java.lang.CharSequence owner, int lease, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void watch(java.lang.CharSequence key, int expectStatus, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}