/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro;

@SuppressWarnings("all")
public interface Mail {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Mail\",\"namespace\":\"avro\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"to\",\"type\":\"string\"},{\"name\":\"from\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"string\"},\"fireandforget\":{\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"null\",\"one-way\":true}}}");
  CharSequence send(Message message) throws org.apache.avro.AvroRemoteException;
  void fireandforget(Message message);

  @SuppressWarnings("all")
  public interface Callback extends Mail {
    public static final org.apache.avro.Protocol PROTOCOL = Mail.PROTOCOL;
    void send(Message message, org.apache.avro.ipc.Callback<CharSequence> callback) throws java.io.IOException;
  }
}